import "./globals.css";
import AuthContext from "../context/Auth";
import ToasterContainer from "@/context/Toaster";
import { Noto_Sans } from "next/font/google";

export const metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

const notoSans = Noto_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  style: "normal",
  variable: "--font-noto-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={notoSans.className}>
      <body className="min-h-screen">
        <ToasterContainer />
        <AuthContext>{children}</AuthContext>
      </body>
    </html>
  );
}
